server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CLIENTE-SERVICE
          uri: lb://CLIENTE-SERVICE
          predicates:
            - Path=/api/cliente/**

        - id: AEROLINE-SERVICE
          uri: lb://AEROLINE-SERVICE
          predicates:
            - Path=/api/airlines/**

        - id: AEROLINE-SERVICE
          uri: lb://AEROLINE-SERVICE
          predicates:
            - Path=/api/flights/**

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/reservations/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/hotel/**

        - id: PAGO-SERVICE
          uri: lb://PAGO-SERVICE
          predicates:
            - Path=/api/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
